.Net Framework/Tahap_2/Actual Result/Zein Mukaffi/ContosoUniversity/ContosoUniversity/Controllers/SiswaaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContosoUniversity.DAL;
using ContosoUniversity.Models;
using ContosoUniversity.ViewModels;


namespace ContosoUniversity.Controllers
{
    public class SiswaaController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Siswaa
        public ActionResult Index()
        {
            ViewBag.students = db.Students.ToList();
            StudentSearch model = new StudentSearch();
            return View(model);
        }

        public ActionResult IndexProses(StudentSearch model, string sortOrder)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.LastSortParm = String.IsNullOrEmpty(sortOrder) ? "last_desc" : "last";

            IEnumerable<Student> students = from s in db.Students
                                            select s;

            //if(ModelState.IsValid){
                if (model.EnrollmentDateFrom != null && model.EnrollmentDateUntil != null)
                {
                    students = students.Where(s => s.EnrollmentDate >= model.EnrollmentDateFrom && s.EnrollmentDate <= model.EnrollmentDateUntil);
                }
                if (!String.IsNullOrEmpty(model.LastName))
                {
                    students = students.Where(s => s.LastName.Contains(model.LastName));
                }
                if (!String.IsNullOrEmpty(model.FirstMidName))
                {
                    students = students.Where(s => s.FirstMidName.Contains(model.FirstMidName));
                }
            //}

            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.FirstMidName);
                    break;
                case "last_desc":
                    students = students.OrderByDescending(s => s.LastName);
                    break;
                case "Date":
                    students = students.OrderBy(s => s.EnrollmentDate);
                    break;
                case "last":
                    students = students.OrderBy(s => s.LastName);
                    break;
                case "date_desc":
                    students = students.OrderByDescending(s => s.EnrollmentDate);
                    break;
                default:
                    students = students.OrderBy(s => s.FirstMidName);
                    break;
            }


            ViewBag.students = students.ToList();
            return View("Index", model);
        }

        // GET: Siswaa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Siswaa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Siswaa/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LastName, FirstMidName, EnrollmentDate")] Student student)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Students.Add(student);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(student);
        }

        // GET: Siswaa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Siswaa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var studentToUpdate = db.Students.Find(id);
            if (TryUpdateModel(studentToUpdate, "",
               new string[] { "LastName", "FirstMidName", "EnrollmentDate" }))
            {
                try
                {
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (DataException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(studentToUpdate);
        }

        // GET: Siswaa/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Siswaa/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Student student = db.Students.Find(id);
                db.Students.Remove(student);
                db.SaveChanges();
            }
            catch (DataException/* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

.Net Framework/Tahap_2/Actual Result/Zein Mukaffi/ContosoUniversity/ContosoUniversity/Views/Siswaa/Create.cshtml
@model ContosoUniversity.Models.Student

@{
    ViewBag.Title = "Tambah Data Mahasiswa";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, "Nama Depan", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control", placeholder = "Your First Name" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Nama Belakang", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Your Last Name" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentDate, "Tanggal Mendaftar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnrollmentDate, new { htmlAttributes = new { @class = "form-control", @type = "date"} })
                @Html.ValidationMessageFor(model => model.EnrollmentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<a href="@Url.Action("Index")" class="btn btn-default">Back</a>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

.Net Framework/Tahap_2/Actual Result/Zein Mukaffi/ContosoUniversity/ContosoUniversity/Views/Siswaa/Delete.cshtml
@model ContosoUniversity.Models.Student

@{
    ViewBag.Title = "Hapus Data Mahasiswa";
}

<h2>Hapus Data</h2>

<h4>Apakah Anda Yakin Ingin Menghapus Data Ini?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.LastName, "Nama Belakang")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.LabelFor(model => model.FirstMidName, "Nama Depan")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>

        <dt>
            @Html.LabelFor(model => model.EnrollmentDate, "Tanggal Mendaftar")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Hapus" class="btn btn-danger" /> 
        <a href="@Url.Action("Index")" class="btn btn-default">Kembali</a> 
    </div>
    }
</div>

.Net Framework/Tahap_2/Actual Result/Zein Mukaffi/ContosoUniversity/ContosoUniversity/Views/Siswaa/Details.cshtml
@model ContosoUniversity.Models.Student

@{
    ViewBag.Title = "Detail Data Mahasiswa";
}

<h2>Detail Data Mahasiswa</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.LastName, "Nama Belakang")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.LabelFor(model => model.FirstMidName, "Nama Depan")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>

        <dt>
            @Html.LabelFor(model => model.EnrollmentDate, "Tanggal Mendaftar")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>
        <dt>
            @Html.LabelFor(model => model.Enrollments, "Detail Pendaftaran")
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Mata Kuliah</th>
                    <th>Nilai</th>
                </tr>
                @foreach (var item in Model.Enrollments)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Course.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Grade)
                        </td>
                    </tr>
                }
            </table>
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Index")" class="btn btn-default">Kembali</a> |
    <a href="@Url.Action("Edit", new { id=Model.ID })" class="btn btn-warning">Edit</a>

</p>

.Net Framework/Tahap_2/Actual Result/Zein Mukaffi/ContosoUniversity/ContosoUniversity/Views/Siswaa/Edit.cshtml
@model ContosoUniversity.Models.Student

@{
    ViewBag.Title = "Edit Data Mahasiswa";
}

<h2>Edit Data Mahasiswa</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, "Nama Depan", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Nama Belakang", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentDate, "Tanggal Mendaftar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnrollmentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnrollmentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Simpan" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<a href="@Url.Action("Index")" class="btn btn-default">Kembali</a>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

.Net Framework/Tahap_2/Actual Result/Zein Mukaffi/ContosoUniversity/ContosoUniversity/Views/Siswaa/Index.cshtml
@model ContosoUniversity.ViewModels.StudentSearch

@{
    ViewBag.Title = "Data Mahasiswa";
    List<ContosoUniversity.Models.Student> students = ViewBag.students;
}

<h2>Data Mahasiswa</h2>


@using (Html.BeginForm("IndexProses", "Siswaa", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    <div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div style="display:flex;">

            @*<===== first name search =====>*@
            <p style="margin-right: 5px; margin-top: 5px;">Cari Nama Depan :</p>
            <p>@Html.EditorFor(model => model.FirstMidName)</p>
            @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            
            @*<===== last name search =====>*@
            <p style="margin-right: 5px; margin-top: 5px; margin-left: 5px;">Cari Nama Belakang :</p>
            <p>@Html.EditorFor(model => model.LastName)</p>
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })

            @*<===== date search from =====>*@
            <p style="margin-right: 5px; margin-top: 5px; margin-left: 5px;">Cari dari Tanggal :</p>
            <p>@Html.EditorFor(model => model.EnrollmentDateFrom, new { @type = "date" })</p>
            @Html.ValidationMessageFor(model => model.EnrollmentDateFrom, "", new { @class = "text-danger" })

            @*<===== date search until =====>*@
            <p style="margin-right: 5px; margin-top: 5px; margin-left: 10px;">Sampai :</p>
            <p>@Html.EditorFor(model => model.EnrollmentDateUntil, new { @type = "date" })</p>
            @Html.ValidationMessageFor(model => model.EnrollmentDateUntil, "", new { @class = "text-danger" })

            @*<===== tombol search =====>*@
            <p><input class="btn btn-info btn-sm" type="submit" style="margin-left: 5px;" value="Cari" /></p>
        </div>

            @*<===== tombol reset =====>*@
            <a style="margin-top: 5px; margin-left:5px;" href="@Url.Action("Index")">Kembali Ke List Awal</a>
    </div>
}

<a href="@Url.Action("Create")" style="margin-bottom: 10px; margin-top: 10px;" class="btn btn-info">Tambah Data [+]</a>

<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.ActionLink("Nama Depan", "IndexProses", new { sortOrder = ViewBag.NameSortParm, FirstMidName = Model.FirstMidName, LastName = Model.LastName, EnrollmentDateFrom = Model.EnrollmentDateFrom, EnrollmentDateUntil = Model.EnrollmentDateUntil })
        </th>
        <th>
            @Html.ActionLink("Nama Belakang", "IndexProses", new { sortOrder = ViewBag.LastSortParm, FirstMidName = Model.FirstMidName, LastName = Model.LastName, EnrollmentDateFrom = Model.EnrollmentDateFrom, EnrollmentDateUntil = Model.EnrollmentDateUntil })
        </th>
        <th>
            @Html.ActionLink("Tanggal Pendaftaran", "IndexProses", new { sortOrder = ViewBag.DateSortParm, FirstMidName = Model.FirstMidName, LastName = Model.LastName, EnrollmentDateFrom = Model.EnrollmentDateFrom, EnrollmentDateUntil = Model.EnrollmentDateUntil })
        </th>
        <th>Opsi</th>
    </tr>

    @foreach (var item in students)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstMidName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentDate)
            </td>
            <td>
                <a href="@Url.Action("Edit", new { id=item.ID })" class="btn btn-warning btn-sm">Edit</a>
                <a href="@Url.Action("Details", new { id=item.ID })" class="btn btn-info btn-sm">Detail</a>
                <a href="@Url.Action("Delete", new { id=item.ID })" class="btn btn-danger btn-sm">Hapus</a>
            </td>
        </tr>
    }
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}